apiVersion: v1
kind: Service
metadata:
  name: "magda-csv-semantic-indexer"
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.port }}
  selector:
    service: magda-csv-semantic-indexer